### ISSUE TITLE
general design issue

### ISSUE THREAD

**Issue by DenisPolygalov** [daharoni/Miniscope_Analysis#4]
In general, you guys made a great work developing Miniscope hardware and firmware, but using Matlab for analysis makes it kind of partial solution. Some researchers will be forced to pay up to 10,000 USD for the Matlab license, depending on the country of usage. Moreover, msAutoSegment2() designed in a way that it loads the _whole_ set of videos into memory, causing Matlab to crash on my 12Gb RAM PC.  Unfortunately the typical case in the nowadays science is when a software developed in a Lab will work in that Lab only and abandoned after The Paper was published. Hope this project will avoid such fate.

**Comment by daharoni** [comment]
Hi Denis,
The main motivation of providing our analysis package is to give labs a jumping off point for their own analysis. The code was mainly written for our internal lab use but should provide anyone looking through it with the general workflow needed for image analysis. I would like to port both our DAQ software as well as analysis to Python but this is currently pretty low on my list of priorities. 

As for msAutoSegment2() taking up a lot of RAM, try applying temporal downsampling to your data to decrease the frame rate to around 5FPS. Also, you might want to check out CNMF analysis (this is what we will be switching to in the future).
