### ISSUE TITLE
msExtractBehavoir() is not backward compatible with older Matlab versions

### ISSUE THREAD

**Issue by DenisPolygalov** [daharoni/Miniscope_Analysis#5]
msExtractBehavoir.m line: 
backgroundIndex = repmat(backgroundIndex,1,1,3); 
In R2011b (and maybe in later releases) repmat does not support such calling syntax (cause "too many input arguments" error). Try guess why this new (and absolutely useless) repmat calling syntax was introduced in the new Matlab releases...

**Comment by daharoni** [comment]
This analysis was written in MATLAB R2013b. It should be easy enough to implement your own repmat function.

**Comment by DenisPolygalov** [comment]
For those who encounter the same issue - just add brackets: 
backgroundIndex = repmat(backgroundIndex,[1,1,3]); 
to make the code backward compatible with Matlab down to R2011b. Also comment 
position = smoothts(position','b',ceil(1/dt))'; 
and 
behav.speed = smoothts(behav.speed','b',ceil(1/dt)); 
lines below in order to get rid of Financial Toolbox dependence. 
You may need to implement/use another smoothing algorithm.
